- name: installing nginx
  ansible.builtin.yum:
    name:
      - nginx
    state: installed

- name: remove a directory & add directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: "{{item}}"
  loop:
    - absent
    - directory

- name: downloading {{ COMPONENT }} component & extracting zip file
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: organizing the content
  ansible.builtin.copy:
    src: /tmp/{{ COMPONENT }}-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes
    follow: yes

- name: copy roboshop conf file
  ansible.builtin.template:
    src: roboshop_conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start frontend service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes



