- name: installing nginx
  ansible.builtin.yum:
    name:
      - nginx
    state: installed

- name: take a download role
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: copy roboshop conf file
  ansible.builtin.template:
    src: roboshop_conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start frontend service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes



