
- name: installing nginx
  ansible.builtin.yum:
    name:
      - nginx
    state: installed

#- name: remove a directory & add directory
#  ansible.builtin.file:
#    path: "{{ APP_LOCATION }}"
#    state: "{{item}}"
#  loop:
#  - absent
#  - directory

#- name: downloading {{ COMPONENT }} component & extracting zip file
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
#    dest: /tmp
#    remote_src: yes
#
#- name: organizing the content
#  ansible.builtin.copy:
#    src: /tmp/{{ COMPONENT }}-main{{ SUFFIX }}
#    dest: "{{ APP_LOCATION }}"
#    remote_src: yes
#    follow: yes

- name: tasks from common role
  ansible.builtin.include_role:
    role: common
    tasks_from: download


- name: copy roboshop conf file
  ansible.builtin.template:
    src: roboshop_conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: copy nginx conf file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

#- name: start frontend service
#  ansible.builtin.systemd:
#    name: nginx
#    state: restarted
#    enabled: yes
#    daemon_reload: yes

- name: task from elk role
  ansible.builtin.include_role:
    role: elk
    tasks_from: filebeats


