 - name: set hostname
  ansible.builtin.shell: set-hostname {{ COMPONENT }}

- name: template a repo file
  ansible.builtin.template:
    src: redis_repo
    dest: /etc/yum.repos.d/redis.repo

- name: installing {{ COMPONENT }}
  ansible.builtin.yum:
    name: redis-6.2.7
    state: installed

- name: update listen ip address
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: start {{ COMPONENT }} service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes
