- name: installing java
  ansible.builtin.yum:
    name:
      - maven
    state: installed

- name: run tasks from common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download

#- name: changes in maven
#  ansible.builtin.shell: mvn clean package  && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
#  args:
#    chdir: /home/roboshop/{{COMPONENT}}


- name: run tasks from common role
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd