- name: install maven YUM module
  ansible.builtin.yum:
    name: maven
    state: installed

- name: import common app setup configuration
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: changes in maven
  ansible.builtin.shell: cd /home/roboshop/{{COMPONENT}} && mvn clean package  && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar

- name: systemd setup for {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

