- name: install frontend
  hosts: FRONTEND
  become: yes
  roles:
    - frontend
  vars:
    ansible_user: centos
    ansible_password: DevOps321

- name: install mongodb
  hosts: MONGODB
  become: yes
  roles:
    - mongodb
  vars:
    ansible_user: centos
    ansible_password: DevOps321

- name: install catalogue
  hosts: CATALOGUE
  become: yes
  roles:
    - catalogue
  vars:
    ansible_user: centos
    ansible_password: DevOps321

- name: install redis
  hosts: REDIS
  become: yes
  roles:
    - redis
  vars:
    ansible_user: centos
    ansible_password: DevOps321

- name: install user
  hosts: USER
  become: yes
  roles:
    - user
  vars:
    ansible_user: centos
    ansible_password: DevOps321

- name: install cart
  hosts: CART
  become: yes
  roles:
    - cart
  vars:
    ansible_user: centos
    ansible_password: DevOps321

- name: install mysql
  hosts: MYSQL
  become: yes
  roles:
    - mysql
  vars:
    ansible_user: centos
    ansible_password: DevOps321
    MYSQL_PASSWORD: RoboShop@1

- name: install shipping
  hosts: SHIPPING
  become: yes
  roles:
    - shipping
  vars:
    ansible_user: centos
    ansible_password: DevOps321

- name: install rabbitmq
  hosts: RABBITMQ
  become: yes
  roles:
    - rabbitmq
  vars:
    ansible_user: centos
    ansible_password: DevOps321
    RABBITMQ_USER_PASSWORD: roboshop123

- name: install payment
  hosts: PAYMENT
  become: yes
  roles:
    - payment
  vars:
    ansible_user: centos
    ansible_password: DevOps321

- name: install dispatch
  hosts: DISPATCH
  become: yes
  roles:
  - dispatch
  vars:
    ansible_user: centos
    ansible_password: DevOps321




