- name: run roboshop file
  hosts: "{{HOST}}"
  become: yes
  # we are getting this from privilegence escalation means becoming an root user for vedio 24/06 1.00hr
  roles:
    - "{{ROLE}}"

# i wrote a simple playbook to run any script. i pass host & role variable through command line to this playbook & thi swill run that particular in partucular host (server)