- name: Install python
  ansible.builtin.yum:
    name:
    - python36
    - gcc
    - python3-devel
    state: installed

- name: run task from common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install specified python requirements using pip3
  ansible.builtin.pip:
    requirements: /home/roboshop/payment/requirements.txt
    executable: pip3

- name: print variable
  ansible.builtin.debug:
    msg: "{{ app_user }}"

- name: Replace a uid & gid
  ansible.builtin.lineinfile:
    path: /home/roboshop/payment/payment.ini
    regexp: '^{{ item.key }}'
    line: "{{ item.value }}"
    loop:
    - { key: 'uid', value: 'uid = {{ app_user.uid }}' }
    - { key: 'gid', value: 'gid = {{ app_user.group }}' }

- name: task from common role
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd
