

- name: Basic deploy of a service
  community.general.terraform:
    project_path: /home/centos/roboshop-ansible/task/s3
    state: present
  when: state == 'apply'
  register: output

- name : see output
  ansible.builtin.debug:
    msg: "{{output.stdout}}"
  when: state == 'apply'

- name: Basic deploy of a service
  community.general.terraform:
    project_path: /home/centos/roboshop-ansible/task/s3
    state: absent
  when: state == 'destroy'
  register: output1

- name : see output
  ansible.builtin.debug:
    msg: "{{output1}}"
  when: state == 'destroy'





    











