route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
- name: "email"
  email_configs:
  - to: "mamidi.ravikumar123@gmail.com"
    from: "mamidi.ravikumar123@gmail.com"
    smarthost: "email-smtp.us-east-1.amazonaws.com:587"
    auth_username: "AKIAQTLUUNRR3UBNZ6ZO"
    auth_password: "BGVCV6d/tNxnX/jKdVRk60jiU/O4/b16yRlnNZjTZ8Lf"
    require_tls: true
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'dev', 'instance']
