- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop
  register: app_user
  when: COMPONENT != frontend

#- name: downloading {{ COMPONENT }} component & extracting zip file
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
#    dest: /home/roboshop
#    remote_src: yes

- name: remove old app content
  ansible.builtin.file:
    path: /home/roboshop/{{ COMPONENT }}
    state: "{{item}}"
  loop:
  - absent
  - directory




