
- name: remove a directory & add directory
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: "{{item}}"
  loop:
  - absent
  - directory

- name: downloading {{ COMPONENT }} component & extracting zip file
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: organizing the content
  ansible.builtin.copy:
    src: /tmp/{{ COMPONENT }}-main{{ SUFFIX }}
    dest: "{{ APP_LOCATION }}"
    remote_src: yes
    follow: yes