- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop

- name: downloading {{ COMPONENT }} component & extracting zip file
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /home/roboshop
    remote_src: yes

- name: remove old app content
  ansible.builtin.file:
    path: /home/roboshop/{{ COMPONENT }}
    state: absent

- name: organizing the content
  ansible.builtin.copy:
    src: /home/roboshop/{{ COMPONENT }}-main/
    dest: /home/roboshop/{{ COMPONENT }}
    remote_src: yes
    follow: yes