- name: set hostname
  ansible.builtin.shell: set-hostname {{ COMPONENT }}

- name: Install botocore & boto3 for AWS secret lookup
  ansible.builtin.pip:
    name:
    - boto3
    - botocore
    executable: pip3