- name: set hostname
  ansible.builtin.shell: set-hostname {{ COMPONENT }}
  when: SECRET_REQ == 'true'

#- name: Install botocore & boto3 for AWS secret lookup
#  ansible.builtin.pip:
#    name:
#    - boto3
#    - botocore
#    executable: pip3
#    msg: "{{ SECRETS.MYSQL_PASSWORD }}"
#  when: SECRET_REQ == 'true'
#  #ignore_errors: true
