- name: set hostname
  ansible.builtin.shell: set-hostname {{ COMPONENT }}

- name: install python module for aws secret manager
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
    executable: pip3
  register: output

- name: pip
  debug:
    msg: "{{ output }}"






