#- name: set hostname
#  ansible.builtin.shell: set-hostname {{ COMPONENT }}

- name: get the variables
  ansible.builtin.debug:
    msg:  "{{ lookup('amazon.aws.aws_secret',  region='us-east-1' ) }}"

#- name: download {{ COMPONENT }} repo file
#  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash
#
#- name: Install the nodejs
#  ansible.builtin.yum:
#    name:
#      - nodejs
#      - npm
#    state: installed
#
#- name: run tasks from common role
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: download
#
#- name: Install packages based on package.json.
#  community.general.npm:
#    path: /home/roboshop/{{ COMPONENT }}
#
#- name: run tasks from common role
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: systemd
#