- name: copy roboshop conf file
  ansible.builtin.template:
    src: service_file
    dest: /etc/systemd/system/{{ COMPONENT }}.service

- name: start "{{ COMPONENT }}" service
  ansible.builtin.systemd:
    name: "{{ COMPONENT }}"
    state: restarted
    enabled: yes
    daemon_reload: yes