- name: Installing nginx
  ansible.builtin.yum:
    name:
      - nginx
    state: present

- name: import common role for component download
  ansible.builtin.include_role:
    name: common
    tasks_from: download.yml
