- name: Template a terraform code
  ansible.builtin.template:
    src: terraform.tf
    dest: /home/centos/main.tf

- name: run terraform code
  ansible.builtin.shell:
    chdir: /home/centos/
    cmd: terraform init


- name: run terraform code
  ansible.builtin.shell:
    chdir: /home/centos/
    cmd: terraform plan



- name: run terraform code
  ansible.builtin.shell:
    terraform apply -auto-approve