- name: Template a terraform code
  ansible.builtin.template:
    src: terraform.tf
    dest: /home/centos/main.tf

- name: run terraform code
  ansible.builtin.shell: |
    terraform init
    terraform plan
  register: output
  chdir: /home/centos/

- name: see output
  debug:
    msg: "{{output}}"


- name: run terraform code
  ansible.builtin.shell:
    terraform apply -auto-approve