- name: Template a terraform code
  ansible.builtin.template:
    src: terraform.tf
    dest: /home/centos/roboshop-ansible/task/main.tf

- name: terraform init
  ansible.builtin.shell: |
    terraform init
    terraform plan 
    terraform apply -auto-approve 
    

    











