- name: Template a terraform code
  ansible.builtin.template:
    src: terraform.tf
    dest: /home/centos/main.tf

- name: run terraform code
  ansible.builtin.shell: |
    cd /home/centos/
    terraform init
    terraform plan
  register: output

- name: see output
  msg: "{{output}}"


- name: run terraform code
  ansible.builtin.shell:
    terraform apply -auto-approve