- name: Template a terraform code
  ansible.builtin.template:
    src: terraform.tf
    dest: /home/centos/roboshop-ansible/task/main.tf

- name: terraform init
  ansible.builtin.shell:
    #chdir: /home/centos/
    cmd: terraform init


- name: terraform plan
  ansible.builtin.shell:
    #chdir: /home/centos/
    cmd: terraform plan



- name: terraform apply -auto-approve
  ansible.builtin.shell:
    terraform apply -auto-approve