- include_tasks: java install

- name: Create an user
  become: yes
  user:
    name: "{{ USER }}"
    state: present

- name: copy file
  copy:
    src: /home/raj/kafka.tgz
    dest: /home/raj

- name: Extract tar file
  #become: yes
  ansible.builtin.unarchive:
    src: /home/raj/kafka.tgz
    dest: "{{ FILE_PATH }}"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: 0755

- name: remove old content
  ansible.builtin.file:
    path: "{{ FILE_PATH }}/kafka"
    state: absent
  ignore_errors: yes

- name: rename the file
  shell: mv {{ FILE_PATH }}/kafka_* {{ FILE_PATH }}/kafka

- name: Update the Java Heap Size for Kafka
  become: yes
  become_user: "{{ USER }}"
  replace:
    path: "{{FILE_PATH}}/kafka/bin/kafka-server-start.sh"
    regexp: 'export KAFKA_HEAP_OPTS=(".+")'
    replace: 'export KAFKA_HEAP_OPTS="-Xmx520M -Xms520M"'
    backup: yes


- name: copy zookeeper & kafka service file
  become: yes
  ansible.builtin.template:
    src: templates/{{ item }}.service
    dest: /etc/systemd/system/{{ item }}.service
    mode: 0755
  loop:
    - zookeeper
    - kafka

- name: copy server.properties file
  ansible.builtin.template:
    src: templates/server.properties
    dest: "{{ FILE_PATH }}/kafka/config/server.properties"

- name: configuring zookeeper
  ansible.builtin.replace:
    path: "{{ FILE_PATH }}/kafka/config/zookeeper.properties"
    regexp: 'clientPort=2181'
    replace: "clientPort={{ ZOOKEEPER_PORT }}"

- name: start zookeeper & kafka service
  become: yes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ item }}"
  loop:
    - zookeeper
    - kafka


- name: Validating if zookeeper is up and listening on port {{ ZOOKEEPER_PORT }}
  wait_for:
    host: "{{ HOST_NAME }}"
    port: "{{ ZOOKEEPER_PORT }}"
    delay: 10
    timeout: 30
    state: started
    msg: "Zookeeper not seem to be running"

- name: Validating if Kafka is up and listening on port  {{ KAFKA_PORT }}
  wait_for:
    host: "{{ HOST_NAME }}"
    port: "{{ KAFKA_PORT }}"
    delay: 10
    timeout: 30
    state: started
    msg: "kafka not seem to be running"





