- name: Install JRE after apt update
  become: yes
  ansible.builtin.apt:
    name: default-jre
    state: present
    update_cache: yes

#- name: Create an user
#  become: yes
#  user:
#    name: "{{ USER }}"
#    state: present


- name: Extract tar file
  become: yes
  ansible.builtin.unarchive:
    src: /home/raj/kafka.tgz
    dest: "{{ FILE_PATH }}"
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: remove old content
  ansible.builtin.file:
    path: "{{ FILE_PATH }}/kafka"
    state: absent
  ignore_errors: yes

- name: rename the file
  shell: mv {{ FILE_PATH }}/kafka_2.11-2.1.1 {{ FILE_PATH }}/kafka

- name: copy zookeeper service file
  become: yes
  ansible.builtin.template:
    src: templates/{{ item }}.service
    dest: /etc/systemd/system/{{ item }}.service
  loop:
    - zookeeper
    - kafka

- name: copy server.properties file
  ansible.builtin.template:
    src: templates/server.properties
    dest: "{{ FILE_PATH }}/kafka/config/server.properties"

- name: configuring zookeeper
  ansible.builtin.replace:
    path: "{{ FILE_PATH }}/kafka/config/zookeeper.properties"
    regexp: 'clientPort=2181'
    replace: "clientPort={{ ZOOKEEPER_PORT }}"

- name: start kafka service
  become: yes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ item }}"
  loop:
    - zookeeper
    - kafka


- name: Validating if zookeeper is up and listening on port {{ ZOOKEEPER_PORT }}
  wait_for:
    port: "{{ ZOOKEEPER_PORT }}"
    delay: 10
    timeout: 30
    state: started
    msg: "Zookeeper not seem to be running"


- name: Validating if Kafka is up and listening on port {{ KAFKA_PORT }}
  wait_for:
    #host: localhost
    port: "{{ KAFKA_PORT }}"
    delay: 10
    timeout: 30
    state: started
    msg: "kafka not seem to be running"

