#- hosts: localhost
#  tasks:

- name: Install JRE after apt update
  become: yes
  apt:
    name: default-jre
    state: present

- name: Create an user
  become: yes
  user:
    name: "{{ USER }}"
    state: present

- name: Extract tar file
  ansible.builtin.unarchive:
    src: /home/{{ USER }}/kafka.tgz
    dest: /home/{{ USER }}
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: remove old content
  ansible.builtin.file:
    path: /home/{{ USER }}/kafka
    state: absent
  ignore_errors: yes

- name: rename tar file
  shell: mv /home/{{ USER }}/kafka_2.11-2.1.1 /home/{{ USER }}/kafka

- name: copy zookeeper service file
  become: yes
  ansible.builtin.template:
    src: templates/{{ item }}.service
    dest: /etc/systemd/system/{{ item }}.service
  loop:
    - zookeeper
    - kafka

- name: copy kafka service file
  ansible.builtin.template:
    src: templates/server.properties
    dest: /home/{{ USER }}/kafka/config/server.properties

- name: start kafka service
  become: yes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ item }}"
  loop:
    - zookeeper
    - kafka


- name: Validating if zookeeper is up and listening on port 2181
  wait_for:
    #host: localhost
    port: "{{ ZOOKEEPER_PORT }}"
    delay: 10
    timeout: 30
    state: started
    msg: "Zookeeper not seem to be running"


- name: Validating if Kafka is up and listening on port 2181
  wait_for:
    #host: localhost
    port: "{{ KAFKA_PORT }}"
    delay: 10
    timeout: 30
    state: started
    msg: "Zookeeper not seem to be running"

