#- name: Fail if "MYSQL_PASSWORD" is undefined
#  ansible.builtin.fail: . This play requires 'MYSQL_PASSWORD'
#  when: MYSQL_PASSWORD is undefined

- name: template a repo file
  ansible.builtin.template:
    src: mysql_repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: start mysql
  ansible.builtin.systemd:
    name: mysqld
    enabled: yes

- name: grep password
  ansible.builtin.shell: "grep 'temporary password' /var/log/mysqld.log | awk  '{print$NF}'"
  register: output

- name:
  ansible.builtin.set_fact:
    MYSQL_DEFAULT_PASSWORD: "{{ output.stdout }}"

- name: print output
  ansible.builtin.debug:
    msg: "{{ MYSQL_DEFAULT_PASSWORD }}"

- name: Fetch MySQL Log File
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: mysql_log

- name: print output
  ansible.builtin.debug:
    msg: "{{ mysql_log['content'] | b64decode | regex_findall('*.temporary.*') }}"