- name: template a repo file
  ansible.builtin.template:
    src: mysql_repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: start mysql
  ansible.builtin.systemd:
    name: mysqld
    enabled: yes

- name: grep password
  ansible.builtin.shell: "grep 'temporary password' /var/log/mysqld.log | awk  '{print$NF}'"
  register: output

- name: print output
  ansible.builtin.debug:
    msg: "{{ output }}"