- name: install go lang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: call common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download

#- name: setting up go
 # ansible.builtin.shell:  go mod init dispatch && go get &&  go build

- name: This command will change the working directory to somedir/
  ansible.builtin.shell:
    cmd:
      - go mod init
      - go get
      - go build
    chdir: /home/roboshop/dispatch

- name: import systemd setup for {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd.yml
