- name: set hostname
  ansible.builtin.shell: set-hostname {{ COMPONENT }}

- name: template a repo file
  ansible.builtin.template:
    src: mongodb_repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: installing mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: update listen ip address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start mongod service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: downloading {{ COMPONENT }} component & extracting zip file
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: load schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}"
    idempotent: yes
  loop:
    - catalogue.js
    - users.js





