- name: prometheus server setup
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: server
  when: SETUP_TYPE == "server"

- name: prometheus client setup
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: server
  when: SETUP_TYPE == "client"