- name: prometheus server configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: prometheus alerts configuration
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: prometheus alerts manager configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/prometheus/alertmanager.yml

- name: restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: check for alert manager activity
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9093
    delay: 10
    timeout: 15

#- name: restart prometheus
#  ansible.builtin.systemd:
#    name: prometheus
#    state: restarted
#
#- name: check for prometheus activity
#  ansible.builtin.wait_for:
#    host: 0.0.0.0
#    port: 9090
#    delay: 10
#    timeout: 15
#
