- name: create appilication user
  ansible.builtin.user:
    name: roboshop
  register: APP_USER

- name: remove app code
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: absent

- name: add app
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: directory

# - name: download & unzip the {{ COMPONENT }} content
#   ansible.builtin.unarchive:
#     src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
#     dest: /tmp
#     remote_src: yes
#
# - name: copy {{ COMPONENT }} code to app location
#   ansible.builtin.copy:
#     src: /tmp/{{COMPONENT}}-main/{{SUFFIX}}
#     dest: "{{ APP_LOCATION }}"
#     remote_src: yes

- name: get latest version of appilication from nexus
  ansible.builtin.shell: curl http://nexus.roboshop.internal:8081/service/rest/repository/browse/{{ COMPONENT }}/ | grep zip | grep "{{ENV}}-{{COMPONENT}}" | sed -e 's/"/ /g' | xargs -n1 | grep ^http | tail -n1
  register: out
  when: APP_VERSION is not defined

- name: declare URL fact of latest version
  ansible.builtin.set_fact:
    URL: "{{ out.stdout }}"
  when:  APP_VERSION is not defined

- name: declare URL fact
  ansible.builtin.set_fact:
    URL: http://nexus.roboshop.internal:8081/repository/{{ COMPONENT }}/{{ENV}}-{{COMPONENT}}-{{APP_VERSION}}.zip
  when: APP_VERSION is defined

- name: download & unzip the {{ COMPONENT }} content from Nexus
  ansible.builtin.unarchive:
    src: "{{ URL }}"
    dest: "{{ APP_LOCATION }}"
    remote_src: yes