- name: install maven YUM module
  ansible.builtin.yum:
    name: maven
    state: installed

- name: import common app setup configuration
  ansible.builtin.include_role:
    name: common
    tasks_from: download

# this step is performed from CI Pipeline
# - name: changes in maven
#   ansible.builtin.shell: mvn clean package  && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
#   args:
#     chdir: /home/roboshop/{{COMPONENT}}

- name: calculate memory
  ansible.builtin.shell: echo "{{ansible_memtotal_mb}} * 0.8" | bc | awk -F . '{print $1}'
  register: mem

- name: systemd setup for {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

- name: filebeat setup
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat
