- name: setting YUM repo for nodejs
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodeJS
  ansible.builtin.yum:
    name: npm
    state: installed

- name: import common role for nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: download

# this step is done from CI pipeline
# - name: Install npm Dependencies
#   community.general.npm:
#     path: "{{ APP_LOCATION }}"
#
- name: import systemd setup for {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd.yml