- name: setup {{ COMPONENT }} systemd service
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service

#not required for immutable
#- name: start {{ COMPONENT }} service
#  ansible.builtin.systemd:
#    name: "{{ COMPONENT }}"
#    enabled: yes
#    state: restarted
#    daemon_reload: yes