- name: copy filebeat repo file
  ansible.builtin.template:
    src: elk.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed
  register: result

- name: copy filebeat conf file
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
  when: result is succeeded

- name: start filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted




