- name: copy filebeat repo file
  ansible.builtin.template:
    src: elk.repo
    dest: /etc/yum.repos.d/filebeat.repo

- name: install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed



