- name: tasks from rsyslog
  ansible.builtin.include_role:
    role: elk
    tasks_from: rsyslog.yml
  when: SETUP_TYPE == 'rsyslog'

- name: tasks from logstash
  ansible.builtin.include_role:
    role: elk
    tasks_from: logstash.yml
  when: SETUP_TYPE == 'logstash'


